# Generated by Django 3.1.7 on 2021-03-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_model',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=1110)),
                ('contact_email', models.CharField(max_length=1110)),
                ('contact_subject', models.CharField(max_length=11100)),
                ('contact_message', models.CharField(max_length=111000)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe_model',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('subscribe_email', models.CharField(max_length=1110)),
            ],
        ),
    ]
